# Generated by Django 6.0.4 on 2026-05-03 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('MERN', 'MERN Stack'), ('DevOps', 'DevOps'), ('QA', 'Quality Assurance'), ('Design', 'UI/UX Design'), ('Data Science', 'Data Science')], max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('score', models.FloatField(default=0)),
                ('certification_count', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
